### ISSUE TITLE
Error: Unable to access jarfile server.jar

### ISSUE THREAD

**Issue by loranger** [PufferPanel/PufferPanel#1116]
Hello,

I'm trying Pufferpanel using docker-compose and it seems it works, but I cannot launch any server.

<details>
<summary>docker-compose.yml</summary>

```yaml
version: '3'

services:

  pufferpanel:
    container_name: pufferpanel
    image: pufferpanel/pufferpanel:latest
    ports:
      - 8080:8080
      - 5657:5657
    volumes:
      - ./config:/etc/pufferpanel
      - ./servers:/var/lib/pufferpanel
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

```

</details>

I've tried a simple minecraft vanilla server, using docker environment.
Installation seems complete, and I can see files from the mount point, but launching server fails

<details>
<summary>server files</summary>

```bash
$ ~/pufferpanel  ls -la la servers/servers/f981400f
total 45M
-rw-r--r-- 1 root root   9 27 janv. 10:35 eula.txt
-rw-r--r-- 1 root root 45M 27 janv. 10:35 server.jar
-rw-r--r-- 1 root root  91 27 janv. 10:35 server.properties
```

</details>

<details>
<summary>f981400j.json</summary>

```json
{
  "type": "minecraft-java",
  "data": {
    "eula": {
      "type": "boolean",
      "desc": "Do you (or the server owner) agree to the <a href='https://account.mojang.com/documents/minecraft_eula'>Minecraft EULA?</a>",
      "display": "EULA Agreement",
      "required": true,
      "value": true
    },
    "ip": {
      "type": "string",
      "desc": "What IP to bind the server to",
      "display": "IP",
      "required": true,
      "value": "0.0.0.0"
    },
    "java": {
      "type": "string",
      "desc": "\"java\" for system standard, else direct path to java",
      "display": "path to java executable",
      "required": true,
      "value": "java",
      "userEdit": true
    },
    "memory": {
      "type": "integer",
      "desc": "How much memory in MB to allocate to the Java Heap",
      "display": "Memory (MB)",
      "required": true,
      "value": 1024
    },
    "motd": {
      "type": "string",
      "desc": "This is the message that is displayed in the server list of the client, below the name. The MOTD does support <a href='https://minecraft.gamepedia.com/Formatting_codes' target='_blank'>color and formatting codes</a>.",
      "display": "MOTD message of the day",
      "required": true,
      "value": "A Minecraft Server\\n\\u00A79 hosted on PufferPanel"
    },
    "port": {
      "type": "integer",
      "desc": "What port to bind the server to",
      "display": "Port",
      "required": true,
      "value": 25565
    },
    "version": {
      "type": "string",
      "desc": "Version of Minecraft to install",
      "display": "Version",
      "required": true,
      "value": "latest"
    }
  },
  "display": "Vanilla - Minecraft",
  "environment": {
    "image": "openjdk:17-alpine",
    "networkMode": "host",
    "type": "docker"
  },
  "install": [
    {
      "target": "server.jar",
      "type": "mojangdl",
      "version": "${version}"
    },
    {
      "target": "server.properties",
      "text": "server-ip=${ip}\nserver-port=${port}\nmotd=${motd}\n",
      "type": "writefile"
    },
    {
      "target": "eula.txt",
      "text": "eula=${eula}",
      "type": "writefile"
    }
  ],
  "id": "f981400f",
  "run": {
    "command": "${java} -Xmx${memory}M -Dlog4j2.formatMsgNoLookups=true -jar server.jar",
    "stop": "stop"
  }
}

```

</details>

<details>
<summary>console logs</summary>

```
DAEMON  Allocating server
DAEMON  Server allocated
DAEMON  Installing server
DAEMON  Version 1.18.1 json located, downloading from https://launchermeta.mojang.com/v1/packages/6ad09383ac77f75147c38be806961099c02c1ef9/1.18.1.json
DAEMON  Version jar located, downloading from https://launcher.mojang.com/v1/objects/125e5adf40c659fd3bce3e66e67a16bb49ecc1b9/server.jar
DAEMON  Downloading: https://launcher.mojang.com/v1/objects/125e5adf40c659fd3bce3e66e67a16bb49ecc1b9/server.jar
DAEMON  Writing some data to file: server.properties
DAEMON  Writing some data to file: eula.txt
DAEMON  Server installed
DAEMON  Starting server
[DAEMON] Starting container
Error: Unable to access jarfile server.jar
DAEMON  Running post-execution steps
```

</details>

What did I miss ? How can I troubleshoot ?

**Comment by LordRalex** [comment]
There is a known limitation of running the panel in Docker where if you run the servers using docker as well, the way that the host docker looks for the files isn't the "same" as what the panel is doing, so it ends up being empty on the host.

The easiest way to solve it is going to be using the /var/lib/pufferpanel path on the host as the server location, so that when the host goes to create the containers, the files are where it can see them

**Comment by karyeet** [comment]
You can also create a symlink in /var/lib/pufferpanel to ./servers 
I do this so I can store servers on a seperate drive.

Make sure **/var/lib/pufferpanel** does not already exist, then just:
`sudo ln -s [path to servers] /var/lib/pufferpanel`

**Comment by loranger** [comment]
Thanks for your support, it works flawlessly now !
I choose both your solutions : I now mount the same pufferpanel lib path:

```yaml
    volumes:
      - ./config:/etc/pufferpanel
      - /var/lib/pufferpanel:/var/lib/pufferpanel
      - /var/run/docker.sock:/var/run/docker.sock
```

And symlinked it to the local `./servers` which allow me to easily backup and manage servers

Thank you so much for your help 👍🏻

**Comment by Nouuu** [comment]
> There is a known limitation of running the panel in Docker where if you run the servers using docker as well, the way that the host docker looks for the files isn't the "same" as what the panel is doing, so it ends up being empty on the host.
> 
> The easiest way to solve it is going to be using the /var/lib/pufferpanel path on the host as the server location, so that when the host goes to create the containers, the files are where it can see them

Solved my problem perfectly, thanks !

**Comment by rienafairefr** [comment]
I'm adding a comment here because this problem and its solution wasn't easy to understand, and offering an alternative workaround without symlinks

This basically boils down to the docker container created by pufferpanel, which looks like this, written as a docker-compose
```
services:
  server-adac1349:
    image: eclipse-temurin:17
    environment:
      - HOME=/pufferpanel
    entrypoint: ["java","-Xmx1024M","-Dlog4j2.formatMsgNoLookups=true","-jar","server.jar","nogui"]
    working_dir: /pufferpanel
    volumes:
      - /var/lib/pufferpanel/servers/adac1349:/pufferpanel
      - /var/lib/pufferpanel/binaries:/var/lib/pufferpanel/binaries
```

The binding (/var/lib/pufferpanel/servers/***) is written from the point of view of the pufferpanel container, the binding is in the go code [here](https://github.com/pufferpanel/pufferpanel/blob/f823e911e4bde483f72227a9d79d92ee42b28c7f/servers/docker/docker.go#L427)

And there is a problem because /var/lib/pufferpanel might not be accessible like this on the host, it might be at /var/lib/docker/volumes/app_pufferpanel-data/_data (if this is a standard local named volume), or it might not be anywhere at all (if the volume uses a Docker volume plugin or whatever).
A full fix (without symlinks or workaround) would inform the pufferpanel docker client of the actual mapping where the /var/lib/pufferpanel/servers/*** is, and add that mapping to the container created

The workaround above, if the servers folder is in a named volume would be 
`ln -s /var/lib/docker/volumes/app_pufferpanel-data/_data/servers /var/lib/pufferpanel/servers`

Another way to do the workaround is having the named volume be actually on the host at /var/lib/pufferpanel/, this way the volume is named and local (usable like any named volume) and there are no symlinks:

```
services:
  pufferpanel:
    image: pufferpanel/pufferpanel
    volumes:
      - pufferpanel-config:/etc/pufferpanel
      - pufferpanel-data:/var/lib/pufferpanel
      - /var/run/docker.sock:/var/run/docker.sock
    # [... other config]
volumes:
  pufferpanel-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/lib/pufferpanel'
  pufferpanel-config
```
