### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by LabodiDavid** [PufferPanel/PufferPanel#1288]
**Is your feature request related to a problem? Please describe.**

I'm running pufferpanel in docker and planning to monitor the health status of the container and I ran into the fact that there is no dedicated solution or an endpoint to check for the service health.

**Describe the solution you'd like**

A /health endpoint would be useful, both in a normal environment and in a docker environment for monitoring. 
It should check the connection state of the database, the daemon, and any other aspects that consider pufferpanel to be in a healthy state.

**Describe alternatives you've considered**
Currently, I'm checking the container's health like this:

```yaml
healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      retries: 3
      timeout: 10s
```
However, this is unreliable because, for example, it may report a healthy status even if it doesn't reach the database.
