### ISSUE TITLE
Docker Network

### ISSUE THREAD

**Issue by LuckCrafter** [PufferPanel/PufferPanel#1404]
**Describe the bug**
If you use a Docker-Template (I used Paper-Minecraft-Docker) the Network Mode will be used as Network Name and the Network Name will be completely ignored. 

```
pufferpanel-1  | [INFO] 2025/03/04 11:26:09 [c2d4d607] Running post execution steps: c2d4d607
pufferpanel-1  | [ERROR] 2025/03/04 11:26:09 [c2d4d607] error starting server c2d4d607: Error response from daemon: network macvlan not found
```

**To Reproduce**
1. Create a new Server from the minecraft-paper-docker template
2. Change Network Mode in the Docker Enviroment to bridge, macvlan or overlay
3. add a name to Network Name
4. Server won't start if there isn't a docker network with the name of the Network Mode.

**Expected behavior**
Creating a Docker network with the name selected in the Network Name box from the type selected in the Network Mode box

**Enviroment**
PufferPanel run on docker on a ArchLinux@6.13.2-arch1-1 host.
Compose file:
```
services:
  pufferpanel:
    image: pufferpanel/pufferpanel:latest
    volumes:
      - ./config:/etc/pufferpanel
      - /var/lib/pufferpanel:/var/lib/pufferpanel
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8999:8080
      - 8998:5657
```
